### ISSUE TITLE
manjaro-i3-minimal-installer

### ISSUE THREAD

**Issue by gpetrousov** [gpetrousov/mydot#15]
Create `mydot` installer for manjaro i3.

Installation wizard flow:

**1 #---`mydot`**
- [x] Fetch `mydot`
- [x] Install `mydot`
- [x] Configure `mydot`

**2 #---base packages**
Packages which are installed using package managers (`pacman` and `pamac`).
- [x] Install base packages

**3 #---install additional packages**
Packages which are not installed using package managers but instead use `shell` and `git`.
- [x] Install additional packages

**4 #---checkout dotfiles**
- [x] Checkout dotfiles

**5 #---apply additional configuration**
- [x] Change shell

**6 #---finalize installation**

**TODO:**
- [x] Remove all other installers
- [x] Update screenshot or remove completely
